spring.application.name=Rent_Flow
spring.datasource.url=jdbc:postgresql://ep-icy-base-anetbtu6-pooler.c-6.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_8oJUrEOa1HQc

spring.datasource.hikari.maximum-pool-size=5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true